version: "2"
services:
  db:
    container_name: ld_db
    image: mysql:8.0.15
    command: '--local-infile=1'
    ports:
      - '32000:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - './db/:/docker-entrypoint-initdb.d/:ro'
  web:
    build: ./Lokdhaba_dj
    container_name: ld_dj
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
    - './Lokdhaba_dj/:/app/'
    ports:
    - "8000:8000"
    links :
    - db
